# 판다스(Pandas)

# 1. 시리즈(Series)

## 1) 생성 및 조회

<table>
    <thead>
        <tr>
            <th>이름</th><th>나이</th><th>키</th>
        </tr>
    </thead>
    <tbody>
        <tr><td>김영철</td><td>24</td><td>179.4</td></tr>
        <tr><td>송윤지</td><td>31</td><td>161.0</td></tr>
        <tr><td>임수현</td><td>26</td><td>174</td></tr>
    </tbody>
</table>

### (1) 데이터만 생성

In [13]:
import pandas as pd

In [ ]:
name_data = pd.Series(data=['김영철', '송윤지', '임수현']) # 안쪽에 튜플이나 넘파이 데이터도 가능
print(name_data)
# 문자열은 다 object로 표현됨

age_data = pd.Series(data=[24, 31,26])
print(age_data)
height_data = pd.Series(data = [179.4, 161.0, 174])
print(height_data)

0    김영철
1    송윤지
2    임수현
dtype: object
0    24
1    31
2    26
dtype: int64
0    179.4
1    161.0
2    174.0
dtype: float64

<table>
    <thead>
        <tr>
            <th>이름</th><th>나이</th><th>키</th>
        </tr>
    </thead>
    <tbody>
        <tr><td>김영철</td><td>24</td><td>179.4</td></tr>
        <tr><td>송윤지</td><td>31</td><td>161.0</td></tr>
        <tr><td>임수현</td><td>26</td><td>174</td></tr>
    </tbody>
</table>

### (2) 인덱스와 함께 생성

In [14]:
age_data = pd.Series(
   data= [24, 31, 26],
   index = ['김영철','송윤지','임수현'] 
)

print(age_data)

김영철    24
송윤지    31
임수현    26
dtype: int64

In [15]:
print(age_data.index)

Index(['김영철', '송윤지', '임수현'], dtype='object')

In [17]:
print(age_data.values)
print(type(age_data.values))

[24 31 26]
<class 'numpy.ndarray'>

## 2) 연산

In [18]:
data1 = pd.Series(data=[10,20,30])
data2 = pd.Series(data=[1,2,3])

data3 = data1 ** data2
print(data3)

0       10
1      400
2    27000
dtype: int64

## 3) 결측치

In [19]:
import pandas as pd
import numpy as np

data = pd.Series([1, np.nan])
print(data)

0    1.0
1    NaN
dtype: float64

### (1) 결측치 발생

In [ ]:
data1 = pd.Series(data=[10,20,30])
data2 = pd.Series(data=[1,2,3,4])

data3 = data1 + data2
print(data3) # 자릿수가 안맞으면 결측으로 표시함

0    11.0
1    22.0
2    33.0
3     NaN
dtype: float64

예제
* 데이터가 10, 20, 30인 시리즈 생성, 인덱스는 부산, 울산, 대구으로 설정
* 데이터가 1, 2, 3, 4인 시리즈 생성, 인덱스는 광주, 부산, 울산, 대구으로 설정
* 데이터의 덧셈

In [ ]:
data1 = pd.Series(data=[10,20,30], index= ['부산','울산','대구'])
data2 = pd.Series(data=[1,2,3,4], index= ['광주','부산','울산','대구'])

data3 = data1 + data2
print(data1)
print(data2)
print(data3)
# 연산은 인덱스 기준으로 이루어진다.

부산    10
울산    20
대구    30
dtype: int64
광주    1
부산    2
울산    3
대구    4
dtype: int64
광주     NaN
대구    34.0
부산    12.0
울산    23.0
dtype: float64

### (2) 결측치 파악

In [ ]:
# info 데이터에 대한 모든것을 알려주는 함수
# 전체갯수(index)와 non-null 갯수로 데이터의 결측치를 확인 가능
data3.info()

<class 'pandas.core.series.Series'>
Index: 4 entries, 광주 to 울산
Series name: None
Non-Null Count  Dtype
--------------  -----
3 non-null      float64
dtypes: float64(1)
memory usage: 236.0+ bytes

### (3) 결측치 채우기
- 평균값을 넣거나 예측을 하여서 넣는다. 혹은 삭제

In [ ]:
data3
#

광주     NaN
대구    34.0
부산    12.0
울산    23.0
dtype: float64

In [36]:
# 결측치 채우기 - 반드시 덮어 씌워줘야 함
data2.fillna(0)
data2 = data2.fillna(0)
print(data2)

광주    1
부산    2
울산    3
대구    4
dtype: int64

In [33]:
# 결측치 판단하기
data3.isna()

광주     True
대구    False
부산    False
울산    False
dtype: bool

In [34]:
# 결측치 판단하기
data3.isna().sum()

np.int64(1)

### (4) 결측치 삭제

In [35]:
# 결측치 삭제 
data3.dropna()

대구    34.0
부산    12.0
울산    23.0
dtype: float64

In [ ]:
data3

In [ ]:
data3.dropna(inplace= True) #변수에 덮어씌우지 않아도 데이터가 덧씌워진다.

In [48]:
a_data = pd.Series(data= ['화인','찬영','유정','윤재'], index= [1,2,3,4])
b_data = pd.Series(data= ['전주','서울','부산'], index= [10,20,30])
print(a_data)
print(b_data)
datasum =  a_data + b_data
print(datasum)
# 인덱스가 같아야지만 연산이 된다

1    화인
2    찬영
3    유정
4    윤재
dtype: object
10    전주
20    서울
30    부산
dtype: object
1     NaN
2     NaN
3     NaN
4     NaN
10    NaN
20    NaN
30    NaN
dtype: object

In [ ]:
a_data = pd.Series(data= ['화인','찬영','유정','윤재'], index= [1,2,3,4])
b_data = pd.Series(data= ['전주','서울','부산'], index= [1,2,3])
print(a_data)
print(b_data)
datasum =  a_data + b_data
print(datasum)

# 인덱스가 같아야지만 연산이 된다

1    화인
2    찬영
3    유정
4    윤재
dtype: object
1    전주
2    서울
3    부산
dtype: object
1    화인전주
2    찬영서울
3    유정부산
4     NaN
dtype: object

In [ ]:
a_data = pd.Series(data= ['화인','찬영','유정','윤재'], index= [1,2,3,4])
b_data = pd.Series(data= ['전주','서울','부산'], index= [1,2,3])
print(a_data)
print(b_data)
datasum =  a_data + b_data
print(datasum)

datasum

1    화인
2    찬영
3    유정
4    윤재
dtype: object
1    전주
2    서울
3    부산
dtype: object
1    화인전주
2    찬영서울
3    유정부산
4     NaN
dtype: object

## 4) 통계

분산은 평균에서 그 값을 뺀 뒤 제곱을 해서 전체 갯수로 나누기
표준편차는 분산의 숫자가 너무 크니까 루트 씌운거

In [38]:
data = pd.Series(data = [10,20,30], index= ['부산','울산','대구'])
data

부산    10
울산    20
대구    30
dtype: int64

In [ ]:
print(data.min()) # 최소
print(data.mean())

In [ ]:
data.describe() # 한번에 볼 수 있게 요약해줌

count     3.0
mean     20.0
std      10.0
min      10.0
25%      15.0
50%      20.0
75%      25.0
max      30.0
dtype: float64

예제. 문자 데이터

```
['HR', 'Engineering', 'HR', 'Engineering', 'HR', 'Marketing', 'Engineering', 'Marketing', 'HR']
```

In [ ]:
data = pd.Series(
    data=['HR', 'Engineering', 'HR', 'Engineering', 'HR', 'Marketing', 'Engineering', 'Marketing', 'HR']
)

data.describe()
# count 갯수 
# unique 중복제거
# top 가장많은거 
# freq 최빈값의 갯수

count      9
unique     3
top       HR
freq       4
dtype: object

# 2. 데이터프레임(DataFrame)

## 1) 생성

<table>
    <thead>
        <tr>
            <th>이름</th><th>성별</th><th>나이</th><th>키</th>
        </tr>
    </thead>
    <tbody>
        <tr><td>김영철</td><th>M</th><td>24</td><td>179.4</td></tr>
        <tr><td>송윤지</td><th>F</th><td>31</td><td>161.0</td></tr>
        <tr><td>임수현</td><th>F</th><td>26</td><td>174</td></tr>
    </tbody>
</table>

In [50]:
data_list = [
    ['김영철','M',24,179.4],
    ['송윤지','F',31, 161.0],
    ['임수현','F',26, 174]
]
data1 = pd.DataFrame(data_list, columns=['이름','성별','나이','키'])
# data.columns = ['이름','성별','나이','키']
data1

    이름 성별  나이      키
0  김영철  M  24  179.4
1  송윤지  F  31  161.0
2  임수현  F  26  174.0

In [51]:
# 열 딕셔너리 이용
data_col_dict = {
    '이름': ['김영철','송윤지', '임수현'],
    '성별': ['M','F','M'],
    '나이': [24,31,26],
    '키': [179.4, 161.0, 174]
}
data2 = pd.DataFrame(data_col_dict)
data2

    이름 성별  나이      키
0  김영철  M  24  179.4
1  송윤지  F  31  161.0
2  임수현  M  26  174.0

In [52]:
# 행 딕셔너리 이용
data_row_list = [
    {'이름': '김영철', '성별': 'M','나이':24,'키': 179.4},
    {'이름': '송윤지', '성별': 'F', '나이':31, '키': 161.0},
    {'이름': '임수현', '성별': 'F', '나이': 26, '키': 174}
]
data3 = pd.DataFrame(data_row_list)
data3

    이름 성별  나이      키
0  김영철  M  24  179.4
1  송윤지  F  31  161.0
2  임수현  F  26  174.0

In [53]:
# 이름 열을 인덱스로 설정하기(덮어쓰기 해야 함)
data4 = data1.set_index('이름')
data4

    성별  나이      키
이름
김영철  M  24  179.4
송윤지  F  31  161.0
임수현  F  26  174.0

In [ ]:
# 이름 인덱스를 다시 열로 바꾸기 (덮어쓰기 해야함)
# 인덱스를 다시 생성해 주는것 0123..아니면 다시 생성함
data5 = data4.reset_index()
data5

    이름 성별  나이      키
0  김영철  M  24  179.4
1  송윤지  F  31  161.0
2  임수현  F  26  174.0

In [55]:
data4

    성별  나이      키
이름
김영철  M  24  179.4
송윤지  F  31  161.0
임수현  F  26  174.0

## 2) 조회

### (1) 이름으로 조회

#### 열 조회

In [57]:
# 나이 열을 조회
data1['나이']

0    24
1    31
2    26
Name: 나이, dtype: int64

In [ ]:
# 나이, 키  열을 조회
data1[['나이','키']] # 리스트 자체는 넣는 개념임 []로 조회하기 때문에

#### 행 조회

In [58]:
data4

    성별  나이      키
이름
김영철  M  24  179.4
송윤지  F  31  161.0
임수현  F  26  174.0

#### 셀 조회

In [59]:
# 송윤지 행 조회
data4.loc['송윤지']

성별        F
나이       31
키     161.0
Name: 송윤지, dtype: object

In [61]:
# 임수현 학생의 키 조회
data4.loc['임수현','키']

np.float64(174.0)

In [ ]:
# 송윤지 학생의 성별 조회
data4.loc['송윤지','성별']

In [60]:
# 김영철, 임수현 행 조회
data4.loc[['김영철','임수현']]

    성별  나이      키
이름
김영철  M  24  179.4
임수현  F  26  174.0

### (2) 인덱스로 조회

In [62]:
data1

    이름 성별  나이      키
0  김영철  M  24  179.4
1  송윤지  F  31  161.0
2  임수현  F  26  174.0

#### 열 조회

In [63]:
데이터프레임.loc[행,열]

NameError: name '데이터프레임' is not defined

In [ ]:
# 나이 열을 인덱스로 조회
data1.iloc[:,2] # 행은 전체 열은 인덱스 2번째 열
# 열을 하나만 추출하면 시리즈로 표현됨

0    24
1    31
2    26
Name: 나이, dtype: int64

In [ ]:
# 성별 키 인덱스로 조회
data1.iloc[:,1:3] # 2개 넣을때 리스트로 표현해도 됨
# 여러개는 데이터 프레임으로 추출됨

  성별  나이
0  M  24
1  F  31
2  F  26

#### 행 조회

In [84]:
data4
# 이름은 인덱스의 이름이다

    성별  나이      키
이름
김영철  M  24  179.4
송윤지  F  31  161.0
임수현  F  26  174.0

In [85]:
# 송윤지 학생의 데이터를 인덱스로 조회
data4.iloc[1,:]

성별        F
나이       31
키     161.0
Name: 송윤지, dtype: object

In [86]:
# 송윤지, 임수현 학생의 데이터를 인덱스로 조회
data4.iloc[1:3,:]

    성별  나이      키
이름
송윤지  F  31  161.0
임수현  F  26  174.0

#### 셀 조회

In [87]:
# 임수현 학생의 성별을 인덱스로 조회
data4.iloc[2,0]

'F'

In [88]:
# 김영철 학생의 키를 인덱스로 조회
float(data4.iloc[0,2])

179.4

### (3) 조건부 조회

In [94]:
# 성별이 M인 데이터 조회
data4[data4['성별'] =='M']

    성별  나이      키
이름
김영철  M  24  179.4

In [96]:
# 키가 170이 넘는 사람들 조회
data4 [data4['키'] > 170]

    성별  나이      키
이름
김영철  M  24  179.4
임수현  F  26  174.0

In [98]:
# 성별이 F이면서 키가 170이상인 사람 조회
data4[(data4['성별']=='F')&(data4['키']>170)]

    성별  나이      키
이름
임수현  F  26  174.0

## 3) 편집

### (1) 인덱스 제거

### (2) 데이터 병합

### (3) 결측치 처리

## 4) 통계

# 3. 실습

## 예제 1.

## 예제 2.

## 예제 3. 자동차 회사의연비 데이터

* manufacturer : 회사명
* cty : 도심연비
* hwy : 고속도로 연비

## 데이터 불러오기

## 데이터 파악하기

## Q1. 몇 개의 회사 데이터가 있나요?

## Q2. 회사별로 참여한 자동차가 몇 대인지 파악하세요.

## Q3. 도심연비와 고속도로 연비를 평균낸 total 연비를 구하세요

## Q4. total 연비 상위 10개 회사의 회사별 개수를 구하세요

## +Quiz. 현대자동차의 평균 total 연비에 대한 평균값은?

## Q5. 평균 total 연비보다 높은 자동차는 PASS, 낮은 자동차는 FAIL로 구분하세요.

## +Quiz. PASS인 자동차 중 가장 많은 숫자의 자동차 회사는?